[ids]

*

[main]

capslock 	= layer(control)
leftcontrol 	= capslock
rightcontrol 	= layer(rightcontrol)

[rightcontrol]

left		= home
right 		= end
up		= volumeup
down		= volumedown
backspace	= delete
esc		= ~

[shift]
*
esc		= `

