# source = $HOME/.cache/wal/colors-hyprland

background {
    monitor =
    path = screenshot

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_passes = 4
    blur_size = 2
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.5
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.64 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgb(282828)
    inner_color = rgb(ebdbb2)
    font_color = rgb(282828)
    fail_color = rgb(cc241d)
    check_color = rgb(d79921)
    fade_on_empty = true
    fade_timeout = 3000
    placeholder_text = <i>Password...</i> # Text rendered in the input box when it's empty.
    hide_input = false
    position = 0, 50
    capslock_color = rgb(cc241d)
    halign = center
    valign = bottom
    fail_timeout = 300
    fail_transition = 200
}

# Current time
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H:%M:%S") </big></b>"
    color = rgb(fbf1c7)
    font_size = 160
    font_family = CaskaydiaCove Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

# User label
label {
    monitor =
    text = <span size="larger">Hey $USER</span>
    color = rgb(fbf1c7)
    font_size = 32
    font_family = CaskaydiaCove Nerd Font 12
    position = 0, -80
    halign = center
    valign = center
}


